export const ConditionsData = [
  { label: "Back Pain" },
  { label: "Cervical Rib" },
  { label: "Scoliosis" },
  { label: "Stenosis" },
  { label: "Spondylosis" },
  { label: "Pelvis Tilting" },
  { label: "Sciatica" },
  { label: "Migraine" },
  { label: "Severe Headache" },
  { label: "Vertigo" },
  { label: "Fibromyalgia" },
  { label: "Numbness" },
  { label: "Rheumatoid Arthritis" },
  { label: "Varicose Veins" },
  { label: "Anxiety" },
  { label: "Rheumatoid Arthritis (RA)" },
  { label: "Hemangioma" },
  { label: "Muscular Dystrophy (MD)" },
  { label: "Parkinson's Disease" },
  { label: "Listhesis" },
  { label: "Post-Accidental Pain" },
  { label: "Pain After Surgery" },
  { label: "Severe Menstrual Pain (Dysmenorrhea)" },
  { label: "Walking Abnormalities" },
  { label: "Ligament Fracture" },
  { label: "Uric Acid Pain" },
  { label: "Knee Pain (Knee Replacement Stage)" },
  { label: "Avascular Necrosis (AVN)" },
  { label: "Pelvic Inflammatory Disease (PID)" },
  { label: "Insomnia (Sleeplessness)" },
  { label: "Liver Cirrhosis" },
  { label: "Fatty Liver" },
  { label: "Liver Enlargement" },
  { label: "Jaundice" },
  { label: "Hepatitis" },
  { label: "Hepatic Coma" },
  { label: "Gallstones" },
];
